--conf spark.metrics.conf.*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
--conf spark.metrics.conf.master.source.jvm.class=org.apache.spark.metrics.source.JvmSource
--conf spark.metrics.conf.driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource
--conf spark.metrics.conf.executor.source.jvm.class=org.apache.spark.metrics.source.JvmSource
--conf spark.metrics.conf.prometheusServlet.path=/metrics

